version: 2.1
orbs:
  aws-s3: circleci/aws-s3@1.0.11
jobs:
  build:
    docker:
      - image: 'circleci/node:14.15.4'
    steps:
      - checkout
      - run:
          name: Installing deps
          command: yarn
      - run:
          name: Project build
          command: CI=false NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL yarn build
      - run:
          name: Project export
          command: yarn export
      - persist_to_workspace:
          root: .
          paths:
            - ./out
  deploy:
    docker:
      - image: 'circleci/python:2.7'
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - aws-s3/sync:
          from: /tmp/workspace/out
          to: 's3://$S3_BUCKET_NAME'
          aws-access-key-id: ACCESS_KEY_ID
          aws-secret-access-key: SECRET_ACCESS_KEY
          aws-region: AWS_REGION
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400"
          overwrite: true
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
      - deploy:
          context: org-global
          requires:
            - build
          filters:
            branches:
              only:
                - master
